### ISSUE TITLE
Error(s) in loading state_dict for ModuleList

### ISSUE THREAD

**Issue by prershen** [caoscott/SReC#10]
I was training with Cityscapes dataset and I trained and saved the weights with no changes to your code. But when Im loading it in eval.py it is giving the following error.

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/gdrive/MyDrive/SReC-master/src/eval.py", line 121, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/content/gdrive/MyDrive/SReC-master/src/eval.py", line 95, in main
    **compressor.nets.load_state_dict(checkpoint["nets"])**
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
**RuntimeError: Error(s) in loading state_dict for ModuleList:**
	**Missing key(s) in state_dict:** "1.0.rgb_decs.0.body.3.weight", "1.0.rgb_decs.0.body.3.bias", "1.0.rgb_decs.1.body.3.weight", "1.0.rgb_decs.1.body.3.bias", "1.0.rgb_decs.2.body.3.weight", "1.0.rgb_decs.2.body.3.bias", "1.1.rgb_decs.0.body.3.weight", "1.1.rgb_decs.0.body.3.bias", "1.1.rgb_decs.1.body.3.weight", "1.1.rgb_decs.1.body.3.bias", "1.1.rgb_decs.2.body.3.weight", "1.1.rgb_decs.2.body.3.bias", "1.2.rgb_decs.0.body.3.weight", "1.2.rgb_decs.0.body.3.bias", "1.2.rgb_decs.1.body.3.weight", "1.2.rgb_decs.1.body.3.bias", "1.2.rgb_decs.2.body.3.weight", "1.2.rgb_decs.2.body.3.bias". 
	**Unexpected key(s) in state_dict**: "1.0.rgb_decs.0.body.4.body.0.weight", "1.0.rgb_decs.0.body.4.body.0.bias", "1.0.rgb_decs.0.body.4.body.2.weight", "1.0.rgb_decs.0.body.4.body.2.bias", "1.0.rgb_decs.0.body.5.weight", "1.0.rgb_decs.0.body.5.bias", "1.0.rgb_decs.0.body.3.body.0.weight", "1.0.rgb_decs.0.body.3.body.0.bias", "1.0.rgb_decs.0.body.3.body.2.weight", "1.0.rgb_decs.0.body.3.body.2.bias", "1.0.rgb_decs.1.body.4.body.0.weight", "1.0.rgb_decs.1.body.4.body.0.bias", "1.0.rgb_decs.1.body.4.body.2.weight", "1.0.rgb_decs.1.body.4.body.2.bias", "1.0.rgb_decs.1.body.5.weight", "1.0.rgb_decs.1.body.5.bias", "1.0.rgb_decs.1.body.3.body.0.weight", "1.0.rgb_decs.1.body.3.body.0.bias", "1.0.rgb_decs.1.body.3.body.2.weight", "1.0.rgb_decs.1.body.3.body.2.bias", "1.0.rgb_decs.2.body.4.body.0.weight", "1.0.rgb_decs.2.body.4.body.0.bias", "1.0.rgb_decs.2.body.4.body.2.weight", "1.0.rgb_decs.2.body.4.body.2.bias", "1.0.rgb_decs.2.body.5.weight", "1.0.rgb_decs.2.body.5.bias", "1.0.rgb_decs.2.body.3.body.0.weight", "1.0.rgb_decs.2.body.3.body.0.bias", "1.0.rgb_decs.2.body.3.body.2.weight", "1.0.rgb_decs.2.body.3.body.2.bias", "1.1.rgb_decs.0.body.4.body.0.weight", "1.1.rgb_decs.0.body.4.body.0.bias", "1.1.rgb_decs.0.body.4.body.2.weight", "1.1.rgb_decs.0.body.4.body.2.bias", "1.1.rgb_decs.0.body.5.weight", "1.1.rgb_decs.0.body.5.bias", "1.1.rgb_decs.0.body.3.body.0.weight", "1.1.rgb_decs.0.body.3.body.0.bias", "1.1.rgb_decs.0.body.3.body.2.weight", "1.1.rgb_decs.0.body.3.body.2.bias", "1.1.rgb_decs.1.body.4.body.0.weight", "1.1.rgb_decs.1.body.4.body.0.bias", "1.1.rgb_decs.1.body.4.body.2.weight", "1.1.rgb_decs.1.body.4.body.2.bias", "1.1.rgb_decs.1.body.5.weight", "1.1.rgb_decs.1.body.5.bias", "1.1.rgb_decs.1.body.3.body.0.weight", "1.1.rgb_decs.1.body.3.body.0.bias", "1.1.rgb_decs.1.body.3.body.2.weight", "1.1.rgb_decs.1.body.3.body.2.bias", "1.1.rgb_decs.2.body.4.body.0.weight", "1.1.rgb_decs.2.body.4.body.0.bias", "1.1.rgb_decs.2.body.4.body.2.weight", "1.1.rgb_decs.2.body.4.body.2.bias", "1.1.rgb_decs.2.body.5.weight", "1.1.rgb_decs.2.body.5.bias", "1.1.rgb_decs.2.body.3.body.0.weight", "1.1.rgb_decs.2.body.3.body.0.bias", "1.1.rgb_decs.2.body.3.body.2.weight", "1.1.rgb_decs.2.body.3.body.2.bias", "1.2.rgb_decs.0.body.4.body.0.weight", "1.2.rgb_decs.0.body.4.body.0.bias", "1.2.rgb_decs.0.body.4.body.2.weight", "1.2.rgb_decs.0.body.4.body.2.bias", "1.2.rgb_decs.0.body.5.weight", "1.2.rgb_decs.0.body.5.bias", "1.2.rgb_decs.0.body.3.body.0.weight", "1.2.rgb_decs.0.body.3.body.0.bias", "1.2.rgb_decs.0.body.3.body.2.weight", "1.2.rgb_decs.0.body.3.body.2.bias", "1.2.rgb_decs.1.body.4.body.0.weight", "1.2.rgb_decs.1.body.4.body.0.bias", "1.2.rgb_decs.1.body.4.body.2.weight", "1.2.rgb_decs.1.body.4.body.2.bias", "1.2.rgb_decs.1.body.5.weight", "1.2.rgb_decs.1.body.5.bias", "1.2.rgb_decs.1.body.3.body.0.weight", "1.2.rgb_decs.1.body.3.body.0.bias", "1.2.rgb_decs.1.body.3.body.2.weight", "1.2.rgb_decs.1.body.3.body.2.bias", "1.2.rgb_decs.2.body.4.body.0.weight", "1.2.rgb_decs.2.body.4.body.0.bias", "1.2.rgb_decs.2.body.4.body.2.weight", "1.2.rgb_decs.2.body.4.body.2.bias", "1.2.rgb_decs.2.body.5.weight", "1.2.rgb_decs.2.body.5.bias", "1.2.rgb_decs.2.body.3.body.0.weight", "1.2.rgb_decs.2.body.3.body.0.bias", "1.2.rgb_decs.2.body.3.body.2.weight", "1.2.rgb_decs.2.body.3.body.2.bias"

Please help me resolve this.

**Comment by Liao1996** [comment]
I also ran into this problem with my self-trained model compression,
How did you solve the problem

**Comment by RowlingJ** [comment]
I ran into the same problem, checked and found that 
in train.py
"""
@click.option("--resblocks", type=int, default=5, show_default=True,
              help="Number of resblocks to use.")
"""
in eval.py
"""
@click.option("--resblocks", type=int, default=3, show_default=True,
              help="Number of resblocks to use.")
"""
These two values should be set to the same
